services:
  api:
    image: api
    ports:
      - 5001:445
      - 5000:80
    build:
      context: .
      dockerfile: src/Api/Dockerfile

  web:
    image: web
    ports:
      - 3001:443
      - 3000:80
    build:
      context: .
      dockerfile: src/Web/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: 1q2w3e4r@#$
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s


volumes:
  restaurantedb: